const fallback=new BroadcastChannel('und-club-online');let socket=null,userName=localStorage.getItem('und-name')||'',currentRoom='',peerNames=[],pendingMessages=[];
const rooms={sushi:{title:'사이버 초밥집',sub:'조용히 함께 먹는 저녁',label:'live sushi bar',html:'<div class="plate"><i class="sushi"></i><i class="sushi"></i><i class="sushi"></i></div>'},smoke:{title:'사이버 흡연장',sub:'잠깐 멈춰 서는 장소',label:'live smoking area',html:'<div class="smoke"><i class="cig"></i></div>'},soft:{title:'사이버 말랑이',sub:'같이 보고 만지는 시간',label:'live tactile room',html:'<div class="ball-stage"><div class="ball"></div></div>'}};
rooms.dance={title:'사이버 댄스룸',sub:'움직임을 공유하는 방',label:'live dance room',html:'<div class="dance-stage"><div class="dancer"></div></div>'};document.querySelector('.rooms').insertAdjacentHTML('beforeend','<article class="room-card"><div><div class="room-top"><span class="room-index">ROOM 04</span><span class="room-status">open</span></div><h2>사이버 댄스룸</h2><p>음악 없이도<br>일단 춤.</p></div><div class="room-art"><div class="dance-stage"><div class="dancer"></div></div></div><button class="enter" data-room="dance">입장하기 →</button></article>');
const $=id=>document.getElementById(id);function showToast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>$('toast').classList.remove('show'),1800)}
function renderRoomUsers(names){const stage=$('stageObject');if(!stage)return;let users=stage.querySelector('.room-users');if(!users){users=document.createElement('div');users.className='room-users';stage.appendChild(users);}users.replaceChildren(...names.map(name=>{const badge=document.createElement('span');badge.className='room-user'+(name===userName?' is-me':'');badge.textContent=name===userName?`${name} (나)`:name;return badge;}));}
function updatePresence(names){const list=[...new Set((names||[]).filter(Boolean))];peerNames=list.filter(name=>name!==userName);$('onlineCount').textContent=String(list.length);$('presence').textContent=list.length>1?`${list.length}명이 함께 있어요`:list.length===1?'나 혼자 있어요':'접속 중인 사람이 없어요';renderRoomUsers(list);}
function send(message){if(socket&&socket.readyState===WebSocket.OPEN){socket.send(JSON.stringify(message));return;}if(socket&&socket.readyState===WebSocket.CONNECTING){pendingMessages.push(message);return;}fallback.postMessage(message)}
function connect(){if(location.protocol==='file:'||socket&&(socket.readyState===WebSocket.CONNECTING||socket.readyState===WebSocket.OPEN))return;socket=new WebSocket((location.protocol==='https:'?'wss://':'ws://')+location.host);socket.onopen=()=>{pendingMessages.splice(0).forEach(message=>socket.send(JSON.stringify(message)));};socket.onmessage=event=>receive(JSON.parse(event.data));socket.onclose=()=>{socket=null;showToast('서버 연결이 끊어졌어요.');};}
function receive(data){if(data.room!==currentRoom)return;if(data.type==='presence')updatePresence(data.names);if(data.type==='chat')addMessage(data.name,data.text,false);if(data.type==='action')applyRoomAction(data.action,data.payload);}
fallback.onmessage=event=>{const data=event.data;if(!data||typeof data!=='object'||data.room!==currentRoom)return;if(data.type==='presence')updatePresence(data.names);if(data.type==='chat')addMessage(data.name,data.text,false);if(data.type==='action')applyRoomAction(data.action,data.payload);};
function setUser(){if(!userName)return;$('userChip').textContent=userName;$('loginModal').classList.add('hidden');connect();}
function enterRoom(room){currentRoom=room;$('lobby').classList.add('hidden');$('roomView').classList.remove('hidden');$('roomTitle').textContent=rooms[room].title;$('roomSub').textContent=rooms[room].sub;$('stageLabel').textContent=rooms[room].label;$('stageObject').innerHTML=rooms[room].html;$('stageObject').className='stage-object '+(room==='sushi'?'sushi-stage':room==='smoke'?'smoke-stage':room==='dance'?'dance-stage':'ball-stage');renderRoomUsers([userName]);$('messages').innerHTML='<div class="message"><b>und club</b><span>이 방에 들어왔어요. 조용히 있어도 괜찮아요.</span></div>';send({type:'join',name:userName,room});}
function addMessage(name,text,mine){const item=document.createElement('div');item.className='message'+(mine?' me':'');item.innerHTML='<b></b><span></span>';item.querySelector('b').textContent=name;item.querySelector('span').textContent=text;$('messages').appendChild(item);$('messages').scrollTop=$('messages').scrollHeight;}
$('loginForm').addEventListener('submit',event=>{event.preventDefault();userName=$('nameInput').value.trim();if(userName){localStorage.setItem('und-name',userName);setUser();}});document.querySelectorAll('[data-room]').forEach(button=>button.addEventListener('click',()=>enterRoom(button.dataset.room)));$('back').addEventListener('click',()=>{$('roomView').classList.add('hidden');$('lobby').classList.remove('hidden');currentRoom='';send({type:'join',name:userName,room:''});});$('chatForm').addEventListener('submit',event=>{event.preventDefault();const input=$('chatInput'),text=input.value.trim();if(!text||!currentRoom)return;addMessage(userName,text,true);send({type:'chat',name:userName,text,room:currentRoom});input.value='';});if(userName){$('nameInput').value=userName;setUser();}
let interactionAudio;
function touchTone(kind){interactionAudio=interactionAudio||new(window.AudioContext||window.webkitAudioContext)();if(interactionAudio.state==='suspended')interactionAudio.resume();const oscillator=interactionAudio.createOscillator(),gain=interactionAudio.createGain();oscillator.type=kind==='crunch'?'square':kind==='sticky'?'sine':'triangle';oscillator.frequency.value=kind==='crunch'?95+Math.random()*75:kind==='sticky'?180:245;gain.gain.setValueAtTime(.0001,interactionAudio.currentTime);gain.gain.exponentialRampToValueAtTime(.07,interactionAudio.currentTime+.01);gain.gain.exponentialRampToValueAtTime(.0001,interactionAudio.currentTime+(kind==='crunch'?.08:.16));oscillator.connect(gain).connect(interactionAudio.destination);oscillator.start();oscillator.stop(interactionAudio.currentTime+(kind==='crunch'?.09:.17));}
function sendRoomAction(action,payload={}){send({type:'action',room:currentRoom,action,payload});}
function playSmoke(){const smoke=document.querySelector('.smoke-stage .smoke');if(!smoke)return;touchTone('crunch');for(let index=0;index<4;index++){const puff=document.createElement('i');puff.className='smoke-puff';smoke.appendChild(puff);setTimeout(()=>puff.remove(),1900);}}
function applyRoomAction(action,payload={}){if(action==='sushi-eat'){const items=[...document.querySelectorAll('.sushi-stage .sushi')],item=items[payload.index];if(!item||item.classList.contains('eaten'))return;item.classList.add('eaten');touchTone('soft');if(items.every(sushi=>sushi.classList.contains('eaten')))setTimeout(()=>items.forEach(sushi=>sushi.classList.remove('eaten')),750);return;}if(action==='smoke'){playSmoke();return;}if(action==='soft-press'){const ball=document.querySelector('.ball-stage .ball');ball?.classList.add('dragging');return;}if(action==='soft-move'){const ball=document.querySelector('.ball-stage .ball');if(ball)ball.style.transform=`translate(${payload.x||0}px,${payload.y||0}px) scale(.91,.84) rotate(-8deg)`;return;}if(action==='soft-release'){const ball=document.querySelector('.ball-stage .ball');ball?.classList.remove('dragging');if(ball)ball.style.transform='';return;}if(action==='dance'){const dancer=document.querySelector('.room-stage .dancer');if(dancer)dancer.style.transform=`translate(${payload.x||0}px,${payload.y||0}px) rotate(${payload.angle||0}deg)`;}}
function activateRoom(room){if(room==='sushi'){document.querySelectorAll('.sushi-stage .sushi').forEach((item,index)=>item.addEventListener('click',()=>{if(item.classList.contains('eaten'))return;applyRoomAction('sushi-eat',{index});sendRoomAction('sushi-eat',{index});}));}if(room==='smoke'){document.querySelector('.smoke-stage .cig').addEventListener('click',()=>{playSmoke();sendRoomAction('smoke');});}if(room==='soft'){const ball=document.querySelector('.ball-stage .ball');let dragging=false,startX=0,startY=0,lastSent=0;ball.addEventListener('pointerdown',event=>{dragging=true;startX=event.clientX;startY=event.clientY;ball.classList.add('dragging');ball.setPointerCapture?.(event.pointerId);touchTone('sticky');sendRoomAction('soft-press');});ball.addEventListener('pointermove',event=>{if(!dragging)return;const x=(event.clientX-startX)/2,y=(event.clientY-startY)/2;ball.style.transform=`translate(${x}px,${y}px) scale(.91,.84) rotate(-8deg)`;const now=Date.now();if(now-lastSent>60){sendRoomAction('soft-move',{x,y});lastSent=now;}});ball.addEventListener('pointerup',()=>{if(!dragging)return;dragging=false;ball.classList.remove('dragging');ball.style.transform='';sendRoomAction('soft-release');});}}
const originalEnterRoom=enterRoom;enterRoom=room=>{originalEnterRoom(room);activateRoom(room);};

document.querySelector('.rooms').addEventListener('click',event=>{const button=event.target.closest('[data-room="dance"]');if(button)enterRoom('dance');});let danceStep=0;document.getElementById('roomStage').addEventListener('click',event=>{if(!event.target.closest('.room-stage .dancer'))return;danceStep++;const moves=[[-34,-7],[28,4],[-14,8],[38,-3],[0,-10]],move=moves[danceStep%moves.length],payload={x:move[0],y:move[1],angle:danceStep%2?12:-12};applyRoomAction('dance',payload);sendRoomAction('dance',payload);});const objectUser=document.createElement('span');objectUser.className='object-user';document.getElementById('roomStage').appendChild(objectUser);setInterval(()=>{objectUser.textContent=typeof userName==='string'&&userName?userName:'';},200);
